FROM webdevops/php-nginx:alpine-php7
RUN apk add --update nodejs nodejs-npm
RUN apk add --no-cache python3 && \
    if [ ! -e /usr/bin/python ]; then ln -sf python3 /usr/bin/python ; fi
EXPOSE 80
EXPOSE 443